[FIX] fix errors in generating invoice pdf
avoinsystems/avoinsystems-addons pull request #3
Opened 2018-03-22 15:04 UTC by mtnarjan

- Fixed a number of errors that prevented generating invoice pdf.
- Added ```include_on_invoice``` field to ```account.journal``` model.

2018-03-23 07:50 UTC, aisopuro requested changes
Muutama pointti, ei mitään kriittistä.

2018-03-23 07:50 UTC, aisopuro commented on l10n_fi_invoice/models/account_journal.py
> +        help="Include this bank account in invoices generated for the associated company",
Johtaako tämä siihen että tili tulostuu kaikille laskuille? Jos ei, niin tässä voisi mainita että se tulee vain suomalaiselle laskulle. Ja `string` voisi silloin olla `Include on Finnish Invoice`.

2018-03-23 07:50 UTC, aisopuro commented on l10n_fi_invoice/views/account_journal_views.xml
> +                <field name="include_on_invoice"/>
Pitäisikö kentän olla näkymätön jos kyseinen `account.journal` ei ole pankki-tyyppinen?

2018-03-23 07:50 UTC, aisopuro commented on l10n_fi_invoice/models/account_invoice.py
> +            .filtered(lambda bank_id: bank_id.journal_id.include_on_invoice)
Mielestäni `filtered` hyväksyy tässä tapauksessa pelkän stringin, jolloin se vain evaluoi josko kyseinen kenttä on True. Eli tässä riittäisi 

```python
self.company_id.partner_id.bank_ids.filtered('journal_id.include_on_invoice')
```

2018-03-24 13:36 UTC, mlaitinen requested changes

2018-03-24 13:36 UTC, mlaitinen commented on l10n_fi_invoice/views/account_journal_views.xml
> +                <field name="include_on_invoice"/>
Atella hyviä pointteja. Testasin omassa ympäristössä ja 1-rivinen lasku heitti maksu-footerin seuraavalle sivulle. Tapahtuuko vain minun ympäristössäni vai onko muotoilussa jokin pulma?

2018-03-29 11:50 UTC, mtnarjan commented on l10n_fi_invoice/views/account_journal_views.xml
> +                <field name="include_on_invoice"/>
Tuon parent elementti näkyy vain pankki-tyyppisillä päiväkirjoilla. Ei tarvitse asettaa tuohon erikseen.

2018-04-03 09:04 UTC, aisopuro commented on l10n_fi_invoice/views/account_journal_views.xml
> +                <field name="include_on_invoice"/>
@mtnarjan taisi korjata tämän, joten nyt voi testata uusiksi @mlaitinen

2018-04-03 09:05 UTC, aisopuro approved these changes

2018-04-04 17:14 UTC, mlaitinen commented
Maksuosuus liikkuu rivejä lisättäessä :/ Mut on tossa toki muitakin kehityskohteita. Mennään tällä nyt.
![finnish_invoice](https://user-images.githubusercontent.com/1525066/38322680-c8ed3b58-3843-11e8-8e0d-a0fa9c32f89b.gif)

2018-04-04 17:14 UTC, mlaitinen approved these changes

2018-04-04 17:15 UTC, merged